### ISSUE TITLE
`README.md` 개선

### ISSUE THREAD

**Issue by solo5star** [GDSC-DEU/2022-SolutionChallenge-CanDrink#40]
## Summary
* README.md 내용을 개선하기

## TODO
- [ ] Top 50 부분에 https://developers.google.com/community/gdsc-solution-challenge/winners 로 링크걸기
- [ ] icon 추가
- [ ] 아키텍트 사진 추가
- [ ] 중복된 여러 개의 LICENSE 항목 하나로 통합

... 이 외에도 추가 사항 있으면 수정해주세요

## References
*None*
