### ISSUE TITLE
여러 종류의 음료수에서 STT를 통해 특정 음료수가 있는지 확인해주는 기능

### ISSUE THREAD

**Issue by solo5star** [GDSC-DEU/2022-SolutionChallenge-CanDrink#46]
## Summary
* 여러 종류의 음료수에서 STT를 통해 특정 음료수가 있는지 알려주는 기능

## TODO
- [ ] 탭을 하는 동안 더 강하게 진동을 울리면서 STT 듣기 모드로 진입
- [ ] STT 듣기 모드에서는 음료수의 이름을 듣고 현재 인식되어있는 음료수 목록에서 찾아야 함
- [ ] 감지 결과를 TTS로 사용자에게 알려주기

## References
* STT 라이브러리: https://pub.dev/packages/speech_to_text
